{% set version = "1.5" %}

package:
    name: django-debug-toolbar
    version: {{ version }}

source:
    fn: django-debug-toolbar-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/d/django-debug-toolbar/django-debug-toolbar-{{ version }}.tar.gz
    md5: 1eb6c9e5fb165807d6003f558df47752

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - django >=1.7
        - sqlparse

test:
    imports:
        - debug_toolbar
        - debug_toolbar.management
        - debug_toolbar.management.commands

about:
    home: https://github.com/django-debug-toolbar/django-debug-toolbar
    license: BSD 3-Clause
    summary: 'A configurable set of panels that display various debug information about the current request/response.'

extra:
    recipe-maintainers:
        - ocefpaf
        - kwilcox
