{% set name = "django-debug-toolbar" %}
{% set version = "3.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-debug-toolbar-{{ version }}.tar.gz
  sha256: 1e3acad24e3d351ba45c6fa2072e4164820307332a776b16c9f06d1f89503465

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django >=3.2
    - sqlparse >=0.2.0

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A configurable set of panels that display various debug information about the current request/response

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
