{% set version = "1.9" %}

package:
  name: django-debug-toolbar
  version: {{ version }}

source:
  fn: django-debug-toolbar-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/django-debug-toolbar/django-debug-toolbar-{{ version }}.tar.gz
  sha256: 39a846374c95e70baf9c92f97db20f15e78ff75a007b67650b79cf8f5e14e27c

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - sqlparse >=0.2.0

test:
  imports:
    - debug_toolbar
    - debug_toolbar.management
    - debug_toolbar.management.commands

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A configurable set of panels that display various debug information about the current request/response.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
