{% set name = "django-debug-toolbar" %}
{% set version = "3.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-debug-toolbar-{{ version }}.tar.gz
  sha256: 95880677ea846ba1077d02305fd5e2b25e1da096e1d4a735b665e3340fa2ae79

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django >=2.2
    - sqlparse >=0.2.0

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A configurable set of panels that display various debug information about the current request/response

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
