{% set version = "1.10" %}

package:
  name: django-debug-toolbar
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-debug-toolbar/django-debug-toolbar-{{ version }}.tar.gz
  sha256: b1cfaf65bd6f48bf1e790d25685190073e8035b4bf3d80741b4beb5efd5a992c

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django >=1.8
    - sqlparse >=0.2.0

test:
  imports:
    - debug_toolbar
    - debug_toolbar.management
    - debug_toolbar.management.commands

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A configurable set of panels that display various debug information about the current request/response.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
