{% set version = "1.7" %}

package:
  name: django-debug-toolbar
  version: {{ version }}

source:
  fn: django-debug-toolbar-{{ version }}.tar.gz
  url: https://github.com/jazzband/django-debug-toolbar/archive/{{ version }}.tar.gz
  sha256: c566d0afa5252288e2dc36c987c14d60ed4e1b684c8ae4413aa76fa4b1e78b14

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - sqlparse >=0.2.0

test:
  imports:
    - debug_toolbar
    - debug_toolbar.management
    - debug_toolbar.management.commands

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'A configurable set of panels that display various debug information about the current request/response.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
