{% set version = "1.6" %}

package:
  name: django-debug-toolbar
  version: {{ version }}

source:
  fn: django-debug-toolbar-{{ version }}.tar.gz
  url: https://github.com/jazzband/django-debug-toolbar/archive/{{ version }}.tar.gz
  sha256: af30aa8d8d22c15099f360f9949a347000d73fb3fc16d7b3e65c78e14a5e9874

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - sqlparse >=0.2.0

test:
  imports:
    - debug_toolbar
    - debug_toolbar.management
    - debug_toolbar.management.commands

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD 3-Clause
  summary: 'A configurable set of panels that display various debug information about the current request/response.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
