{% set version = "3.2.1" %}

package:
  name: django-debug-toolbar
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-debug-toolbar/django-debug-toolbar-{{ version }}.tar.gz
  sha256: a5ff2a54f24bf88286f9872836081078f4baa843dc3735ee88524e89f8821e33

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - django >=1.11
    - sqlparse >=0.2.0

test:
  imports:
    - debug_toolbar
    - debug_toolbar.management
    - debug_toolbar.management.commands

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A configurable set of panels that display various debug information about the current request/response

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
