{% set name = "django-debug-toolbar" %}
{% set version = "3.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 24ef1a7d44d25e60d7951e378454c6509bf536dce7e7d9d36e7c387db499bc27

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django >=3.2.4
    - sqlparse >=0.2.0

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-debug-toolbar/django-debug-toolbar
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A configurable set of panels that display various debug information about the current request/response

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
