travis:
  secure:
    BINSTAR_TOKEN: K9fq0eXslcMCWR0WMZgdZR/AY20uWxaL9PJiXJ9LB4qkjwcEyhLtRjYtDwXDdmZQo2HusVMfu2AM+P4V8ukT0+Sfsup6rYe7dqZV4NuuaPMdl3XervjTOWoE1YYGJgJ+8nB8BksqNcair5GffVOoM/gy5srXsHhwCD8IJLwrISG5lgLx4aGGNWSrzDofgZZ80kcbM06xlk5dEFVEfb9IB9PG86IoS5+2eR5NcQ4Qs9c5jYSeHLSb2maxb3IsP59iXvN4eosU7R47ZK2kXpPbwpzcxjY1FxeZmF7NtaNOXqgxE2RJKIGxbtihanY+FoZOrFZp5u1eMwXK53Io7w6s/Y4fXPwqIgncjoz/6f2sZuEMOMm+j45CLQkgZYHhvEbHMvsOJZobWDcaa+UlvX3G66F9i8M3NvXFH5Of8/+jLfq66Am1yvmzwu/qTggRxuDCBbn0wMxMnc0A/A4Famko5Hk9z/gtvJcxcnvbSkXje2QPKhYDN1J10gTZhzx3/0l1Lxk9lfmbZIfmT0SErN4Zk4NxHuYz/CUIr1ofXm7wFZ3i9VF2lwPpg8xb3Z4u5qTSVt/x1ZQvOsyj8p4jcyEuT2I7YNLZ8q05lRPsndpd4cD2899wiCc5RMvlXilCdlv8tZ1yXpsdWHnlDm0AD1eernLPKTsrdeMvs3vhDIlmUmw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
