travis:
  secure:
    BINSTAR_TOKEN: hgKx1Gkk+UIdEv4HG2bV4lGWWIrXQM5YN1MIsjzSYw6tiZ+WCTWAsQjWpv3JZgrBZkkR47HTT5u4PwA7aUDrPsZSdwTq6GbPjFZUH0Ujl/1E8C0FCOXY5hawTanCIGcr9gcgXQQcjKQXAqTveabk0N18gyDizQF+TFgitXp5xCQktvQDqGDo/Q+zZ1OprUtuB9mvehscdbV7vcwb3HAkt7QAag4hevIIsHnrjGdOnEYPMihOYCvC0O3/NTjy2KwdCuk1raV13oZ77s+L8ZsAVXxJzHM78ceiUMTSostMx639dfHHfTtD5vVLmSJmrbMEgi3glALw1CHh6ScQ8XBXFTfoiqKZVdG1kA1/pSj8dCiuxcu/OcHSZyItUBBJ4NrYJJ32pGUoBYdrxcUkOB2wzWY3wTkgPr5IvOQi/iatrRjX1LF0RnlCZpdQTM2O9HyDd2n9ND2qCvaxlwIadcXj2qlixlxb9F8JttNpkW1xBeJPW8uBGujnw8swORBcN6yFF0aeg3KaMsYdyMWU73XDPapiMh8O/64Re8CTnMuPKs53bVE/A7xooQDwUfgIt71T8WMtOFtvOKb35z+1eGTNFCnl+8zoS/CgtV7WGnwYdGjRCF++QKxjVWMSkiAxIrAmMqy0TO5nzbY490LMr63SC6Ipj4doLl+QVsAfN6n2EqM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
